name: deploy structurizr workspace to Planetary Quantum

on:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use the Structurizr CLI to validate
        run: |
          docker run -i --rm -v $PWD/data:/data structurizr/cli validate -w /data/bbnavi.dsl
  deploy:
    needs: validate
    runs-on: ubuntu-latest
    container: r.planetary-quantum.com/quantum-public/cli:2
    env:
      QUANTUM_USER: ${{ secrets.QUANTUM_USER }}
      QUANTUM_PASSWORD: ${{ secrets.QUANTUM_PASSWORD }}
      QUANTUM_ENDPOINT: "tpwd-bb-navi"
      QUANTUM_STACK: "structurizr"
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Planetary Quantum
        run: quantum-cli stacks update --create --wait
